### ISSUE TITLE
Arduino Error - error: 'class Adafruit_NeoPixel' has no member named 'updateLength'    rgb.updateLength(ledCount);

### ISSUE THREAD

**Issue by YMLkris** [sparkfun/Blynk_Board_ESP8266#6]
Hello all,

When compiling the firmware in the Arduino IDE, I am getting error messages in both files which use rgb.updateLength. I have installed / updated all of the libraries listed, including Adafruit NeoPixel.  The error is:

Arduino: 1.6.11 (Mac OS X), Board: "SparkFun Blynk Board, 80 MHz, Serial, 115200, 4M (1M SPIFFS)"

/Users/kriss/Documents/Arduino/Blynk_Board_ESP8266/Firmware/BlynkBoard_Core_Firmware/BlynkBoard_BlynkMode.ino: In function 'void BlynkWidgetWrite29(BlynkReq&, const BlynkParam&)':
BlynkBoard_BlynkMode:373: error: 'class Adafruit_NeoPixel' has no member named 'updateLength'
   rgb.updateLength(ledCount);
       ^
/Users/kriss/Documents/Arduino/Blynk_Board_ESP8266/Firmware/BlynkBoard_Core_Firmware/BlynkBoard_Setup.ino: In function 'void performSelfTest()':
BlynkBoard_Setup:337: error: 'class Adafruit_NeoPixel' has no member named 'updateLength'
   rgb.updateLength(2); // Connect to testbed LED
       ^
Multiple libraries were found for "Servo.h"
 Used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/Servo
 Not used: /Applications/Arduino.app/Contents/Java/libraries/Servo
Multiple libraries were found for "Adafruit_NeoPixel.h"
 Used: /Users/kriss/Documents/Arduino/libraries/Adafruit_NeoPixel
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/Adafruit_NeoPixel
Multiple libraries were found for "BlynkSimpleEsp8266.h"
 Used: /Users/kriss/Documents/Arduino/libraries/Blynk
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/Blynk
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/Blynk
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/Blynk
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/Blynk
Multiple libraries were found for "SparkFunHTU21D.h"
 Used: /Users/kriss/Documents/Arduino/libraries/SparkFun_HTU21D_Humidity_and_Temperature_Sensor_Breakout
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/SparkFun_HTU21D_Humidity_and_Temperature_Sensor_Breakout
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/SparkFun_HTU21D_Humidity_and_Temperature_Sensor_Breakout
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/SparkFun_HTU21D_Humidity_and_Temperature_Sensor_Breakout
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/SparkFun_HTU21D_Humidity_and_Temperature_Sensor_Breakout
Multiple libraries were found for "SparkFunTSL2561.h"
 Used: /Users/kriss/Documents/Arduino/libraries/SparkFun_TSL2561
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/SparkFun_TSL2561
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/SparkFun_TSL2561
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/SparkFun_TSL2561
 Not used: /Users/kriss/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/SparkFun_TSL2561
exit status 1
'class Adafruit_NeoPixel' has no member named 'updateLength'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by bboyho** [comment]
Hi,

There are two things that might be causing the compile error. If you do not have the library installed to the correct path, the Arduino IDE will have issues compiling since it is not able to understand the functions defined. This is a common issue.  For more information, check out the tutorial on installing the library using the [Arduino Library Manager](https://learn.sparkfun.com/tutorials/installing-an-arduino-library/all#using-the-arduino-library-manager). Simply search for "**NeoPixel**" to automatically install the [NeoPixel library](https://github.com/adafruit/Adafruit_NeoPixel).

Also, make sure that you have the following files in the [same folder as the **BlynkBoard_Core_Firmware.ino**](https://github.com/sparkfun/Blynk_Board_ESP8266/tree/master/Firmware/BlynkBoard_Core_Firmware) or you will have issues compiling:

* BlynkBoard_BlynkMode.ino
* BlynkBoard_ConfigMode.ino
* BlynkBoard_Setup.ino
* BlynkBoard_settings.h

The **BlynkBoard_settings.h** file is where `rgb` is defined so that we can use the library => [https://github.com/sparkfun/Blynk_Board_ESP8266/blob/master/Firmware/BlynkBoard_Core_Firmware/BlynkBoard_settings.h#L110]9https://github.com/sparkfun/Blynk_Board_ESP8266/blob/master/Firmware/BlynkBoard_Core_Firmware/BlynkBoard_settings.h#L110) .
